/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ApiPublicRouteRouteImport } from './routes/api/public/route'
import { Route as ApiPublicExampleIndexRouteImport } from './routes/api/public/example/index'

const ApiPublicRouteRoute = ApiPublicRouteRouteImport.update({
  id: '/api/public',
  path: '/api/public',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExampleIndexRoute = ApiPublicExampleIndexRouteImport.update({
  id: '/example/',
  path: '/example/',
  getParentRoute: () => ApiPublicRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/api/public': typeof ApiPublicRouteRouteWithChildren
  '/api/public/example/': typeof ApiPublicExampleIndexRoute
}
export interface FileRoutesByTo {
  '/api/public': typeof ApiPublicRouteRouteWithChildren
  '/api/public/example': typeof ApiPublicExampleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/api/public': typeof ApiPublicRouteRouteWithChildren
  '/api/public/example/': typeof ApiPublicExampleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/api/public' | '/api/public/example/'
  fileRoutesByTo: FileRoutesByTo
  to: '/api/public' | '/api/public/example'
  id: '__root__' | '/api/public' | '/api/public/example/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ApiPublicRouteRoute: typeof ApiPublicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/api/public': {
      id: '/api/public'
      path: '/api/public'
      fullPath: '/api/public'
      preLoaderRoute: typeof ApiPublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/example/': {
      id: '/api/public/example/'
      path: '/example'
      fullPath: '/api/public/example/'
      preLoaderRoute: typeof ApiPublicExampleIndexRouteImport
      parentRoute: typeof ApiPublicRouteRoute
    }
  }
}

interface ApiPublicRouteRouteChildren {
  ApiPublicExampleIndexRoute: typeof ApiPublicExampleIndexRoute
}

const ApiPublicRouteRouteChildren: ApiPublicRouteRouteChildren = {
  ApiPublicExampleIndexRoute: ApiPublicExampleIndexRoute,
}

const ApiPublicRouteRouteWithChildren = ApiPublicRouteRoute._addFileChildren(
  ApiPublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ApiPublicRouteRoute: ApiPublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
